### ISSUE TITLE
Which pdf-style is preferred?  

### ISSUE THREAD

**Issue by kito-cheng** [riscv/docs-templates#12]
I saw there is two pdf-style file, `alt2-theme.yml` and `risc-v_spec-pdf.yml`, which is preferred or suggested one?

**Comment by cetola** [comment]
I'll ask @elisa-riscv to go into detail here, but we will refine this so there is only 1 template option.

**Comment by elisa-riscv** [comment]
Thanks for asking this question. My apologies for the fact that I had been waiting for feedback on preferences. There was very little feedback at all, however. Any expressed preference was towards a serif font.

Today I updated the command for a local build with the current file structure: 

 asciidoctor-pdf -r asciidoctor-mathematical -a mathematical-format=svg -r asciidoctor-bibtex -r asciidoctor-diagram book_header.adoc -a pdf-style=resources/themes/alt2-theme.yml -a pdf-fontsdir=resources/alt2-fonts/

Tomorrow I will change the file structure and update the command.

**Comment by kito-cheng** [comment]
Thanks for clarify that! I'll sync that pdf-style with psABI document.

So I leave this issue open, and feel free to close this once you has update the doc :)

**Comment by elisa-riscv** [comment]
I have deleted the minimal serif fonts, changed the names of both the fonts directory and the YAML file, and changed the command for the build in the README. If you do a pull, you will need to refer to the updated names for the YAML and for the font directory.
