### ISSUE TITLE
Ruby 2.5.9?

### ISSUE THREAD

**Issue by tariqkurd-repo** [riscv/docs-templates#5]
ALERT: Ensure that you are using Ruby 2.5.9 for all gems that you install for the Asciidoctor toolchain.

http://rubyinstaller.org/

does this mean that I should download ruby 2.5.9 from rubyinstaller.org? Because that version isn't apparently available.

**Comment by tariqkurd-repo** [comment]
except for the mathematical gem all is working

**Comment by elisa-riscv** [comment]
You should install RVM and then use RVM to install Ruby 2.5.9.

**Comment by elisa-riscv** [comment]
I'm making note of the fact that the Ruby Asciidoctor toolchain makes use of Prawn for building PDF output, and that Prawn went for a few years without updates, then was updated in 2020. It looks like there will be another update in 2021. I have not yet looked into the details and wonder if some of the Ruby gems that are essential for specific features required for professional level pdfs will likewise be updated. Until that time the most promising workaround is to make use of Cygwin.

**Comment by elisa-riscv** [comment]
I am closing this issue and leaving #4 open because of the direct and intertwined relationship between the two issues.
