### ISSUE TITLE
wavedrom rendering for 16-bit encodings

### ISSUE THREAD

**Issue by tariqkurd-repo** [riscv/docs-templates#6]
https://github.com/riscv/riscv-code-size-reduction/blob/master/Zce-release-candidate/c_mul.adoc

for example - the wavedrom encoding diagram is 32-bit wide, but it's only a 16-bit encoding.
Is there a way of configuring it to be only 16-bits?

also, this one for example:

https://github.com/riscv/riscv-code-size-reduction/blob/master/Zce-release-candidate/c_sb.adoc

the necessary text doesn't fit in the boxes if you render the file - how can I fix that?

Thanks!

Tariq

**Comment by cetola** [comment]
[c_mul.pdf](https://github.com/riscv/docs-templates/files/6802702/c_mul.pdf)
[c_sb.pdf](https://github.com/riscv/docs-templates/files/6802703/c_sb.pdf)

Able to reproduce in macOS. Will look into this.

**Comment by cetola** [comment]
Please try adding the config option to the reg class. Example from c_mul:
```
{reg:[
     { bits:  3, name: 0x4, attr: ['FUNCT3'] },
    { bits:  3, name: 0x7, attr: ['TBD'] },
    { bits:  3, name: 'rsd\'' },
     { bits:  2, name: 0x2, attr: ['TBD'] },
     { bits:  3, name: 'rs2\'' },
     { bits:  2, name: 0x1, attr: ['C1'] },
],config:{bits:16}}
```

Let me know if that fix is what you are looking for.

[c_mul.pdf](https://github.com/riscv/docs-templates/files/6802813/c_mul.pdf)

**Comment by elisa-riscv** [comment]
Perhaps I can gather some FAQs on using Wavedrom...

**Comment by tariqkurd-repo** [comment]
yes, that's perfect, thanks!
